### ISSUE TITLE
root/file object as argument

### ISSUE THREAD

**Issue by lanttu** [malijs/mali#1]
You can specify import root directory by using `{ root: "dir", file: "subdir/file.proto" }` style object argument in `grpc.load` method, see https://github.com/dcodeIO/protobuf.js/blob/ProtoBuf5/README.md#loading-proto-files However, this cannot be achieved in mali since `grpc.load` is called only if the first argument is string.

**Comment by bojand** [comment]
Note that you can just use [`path.resolve()`](https://nodejs.org/dist/latest-v6.x/docs/api/path.html#path_path_resolve_paths) to build the path for the `.proto` file.

**Comment by lanttu** [comment]
Yeah that works too, but only if proto file doesn't have imports or imports files only from the same directory (not totally sure about the last one). 

Let's say we have following files:
```
pb/
  sub1/
    a.proto
    b.proto
  sub2/
    c.proto
```

Now `a.proto` needs stuff from `b.proto` and `c.proto`. This doesn't work unless I use `{ root: "pb", file: "sub1/a.prpto"}` as argument. `a.proto` would look something like this:
```
// a.proto
import "sub1/b.proto"
import "sub2/c.proto"
...
```

**Comment by bojand** [comment]
Ok thanks for explaining the issue, I understand it better now. Will try and address this soon-ish when I can, hopefully I can come up with a sensible backwards-compatible way of doing it; but I may have to change the API, in which case it will come in as version `0.2.0`.

**Comment by lanttu** [comment]
I'm willing to do it if you have some idea how to do it without breaking anything.

**Comment by bojand** [comment]
Hello, added support for this. Just use an object specifying those options as the first param, instead of a path.

```
const app = new Mali({ root: 'pb', file: 'sub1/a.prpto' }, 'MyService')
```

And it should work. Let me know if there are issues.
