### ISSUE TITLE
Protobufjs6 support

### ISSUE THREAD

**Issue by lanttu** [malijs/mali#10]
gRPC supports Protobufjs6 nowadays. However, since you have to use `grpc.loadObject(pb6Object)` instead of `grpc.load(file)` the support with Mali is not that straightforward. I'd like  to be able to use something like this
```js
const pb = grpc.loadObject(protobufjs6.loadSync('services.proto'));
const mali = new Mali(pb);
mali.use('services.TestService', mw);
```
One possibility would be to change Mali constructor so that it only accepts gRPC object (result of either `load()` or `loadObject()`) as an argument. That would simplify the init and also decouple loading gRPC from Mali.

**Comment by lanttu** [comment]
Yeah, they switched dependency back to version 5 meaning that `load` will behave like 5, but the `loadObject` method supports also version 6 objects. At least that's how I understood it.

I fiddled a bit and added the support for protobufjs6 (and package prefix) in this commit https://github.com/IndoorAtlas/mali/commit/8fd6eb03e7f155c10a2c3a1cba26aa4f13bbe50e in a very quick&dirty way. Seems to work at least for our current use case.

**Comment by bojand** [comment]
Hello, I think I have added what's required for this. Most of the work went into [grpc-inspect](https://github.com/bojand/gprc-inspect) module. You can see the changes and sample usage in PR #11. Please provide any comments there. Thanks.
