### ISSUE TITLE
Question: Exposing a route path

### ISSUE THREAD

**Issue by aiosifelis** [malijs/mali#102]
Is it possible to expose a route by exposing a path in a Mali server instance? Probably by enhancing express?

**Comment by bojand** [comment]
Hello,

I am not sure I understand the question. Can you please elaborate. Mali is a framework on top of gRPC, which works _strictly_  using http2. Express is an router / framework for http1 for web / REST services. The two are not very compatible.

**Comment by aiosifelis** [comment]
Hello, thank you for your response. I asked the question thinking about Apollo Server where you can add express as a middleware to enhance the express framework functionality. But then I read your answer and you are right. Thanks for your time.
