### ISSUE TITLE
Start hook?

### ISSUE THREAD

**Issue by snnsnn** [malijs/mali#122]
Hi, thank you for the great work.

I was wondering if there is any hook that fires when the app has started successfully.

People using something like this, but this does not provide any assurance:
```
const PORT = '[::1]:50001';
app.use({ greet });
console.log('Listening on port ' + PORT);
app.start(PORT);
```

**Comment by bojand** [comment]
Hello, can you elaborate further on what's the issue exactly? `start` does some extra work and then calls the underlying [start](https://grpc.github.io/grpc/node/grpc.Server.html#start__anchor) method. When start returns the server is ready to handle requests, so the following would be sufficient:

```js
const PORT = '[::1]:50001';
app.use({ greet });
app.start(PORT);
console.log('Listening on port ' + PORT);
```

**Comment by snnsnn** [comment]
I was asking for something like a node server callback:

```javascript
server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```
Callback runs only after successful port binding, in this case terminal output is sure sign of successful start.

But with this code it feels like you get the terminal output even if you get  an error in preceding code assuming use and start is async code: 
```
app.start(PORT);
console.log('Listening on port ' + PORT);
```

**Comment by bojand** [comment]
`app.start()` _was_ sync function. With [0.30.0](https://github.com/malijs/mali/releases/tag/v0.30.0) `app.start()` is async.
