### ISSUE TITLE
Cancelling response streams

### ISSUE THREAD

**Issue by rafamel** [malijs/mali#129]
When handling a response stream, is it possible to cancel further responses from the client, and react to it on the server, hence allowing for the release of server resources that might continue to handle the subscription to that stream? I'm thinking about potential subscriptions that we might want cancelled once the client chooses to stop listening to them. Here's a relevant [related issue regarding the same concern for Apollo](https://github.com/apollographql/graphql-subscriptions/issues/141).

I'm fairly new to gRPC, so forgive me if this is out of place. In any case, otherwise, would it be suitable to use a duplex stream to notify on cancellation?

**Comment by bojand** [comment]
What kind of call is this exactly? Client Streaming, Server Streaming, or Duplex? Either way depending on what you wish to accomplish there should be mechanism in the underlying grpc `call` object. 

On client side, if the client unexpectedly has to stop the stream in the middle, you can cancel the call using `call.cancel()`. Note that this will terminate the call with a `CANCELLED` status.

On the server side, the `call` is a stream so you can call `end()` if it's Writable or Duplex, or `destroy()` with an optional error in case of readable. Alternatively you can call `resume()` when the readable stream is not paused to drain the stream and close it. It depends on your context. Please see [stream](https://nodejs.org/api/stream.html) documentation.

**Comment by rafamel** [comment]
Hi @bojand , thanks for the answer! The context would be server streaming, with the client cancelling the stream at some point. The question would be, when that happens (server is streaming, client cancels), how do we react to it on the server to free up server resources? Ex. the server stream was dependent on a subscription to a service, and we want to unsubscribe from it server side.

Sorry if that was unclear.

**Comment by bojand** [comment]
Hello,

On client side you can just do `call.cancel()` when you need to cancel. On server you will receive `cancelled` event where you can clean up resources. Here is a contrived example adapted from route chat gRPC example to demonstrate:

client:

```js
function runRouteChat (callback) {
  var call = client.routeChat()

  var i = 0

  var notes = [{
    message: 'First message'
  }, {
    message: 'Second message'
  }, {
    message: 'Third message'
  }, {
    message: 'Fourth message'
  }, {
    message: 'Fifth message'
  }]

  call.on('data', function (note) {
    console.log('Got message: ' + note.message)

    if (i === 3) {
      call.cancel()
      return
    }
    if (i < notes.length) {
      var noteToSend = notes[i]
      i++

      console.log('Sending message: ' + noteToSend.message)
      call.write(noteToSend)
    } else {
      console.log('ending...')
      call.end()
    }
  })

  call.on('error', status => {
    console.log('error: ' + status)
  })

  call.on('end', callback)

  var note = notes[i]
  console.log('Sending message "' + note.message)
  i++
  call.write(note)
}
```

and server side:

```js
async function routeChat (ctx) {
  console.log('route chat')

  ctx.call.on('cancelled', () => {
    console.log('server: request cancelled')
  })

  ctx.call.on('error', status => {
    console.log('server error: ' + status)
  })

  ctx.call.on('end', () => {
    console.log('server end')
    ctx.res.end()
  })

  ctx.call.on('data', data => {
    console.log('server data: ' + data.message)
    data.message = data.message.toUpperCase()
    ctx.res.write(data)
  })
}
```

Client logs:

```
Sending message "First message
Got message: FIRST MESSAGE
Sending message: Second message
Got message: SECOND MESSAGE
Sending message: Third message
Got message: THIRD MESSAGE
error: Error: 1 CANCELLED: Cancelled
```
and server logs:
```
route chat
server data: First message
server data: Second message
server data: Third message
server end
server: request cancelled
```

**Comment by rafamel** [comment]
Hi @bojand, thanks! That was very **very** helpful.

Congrats on mali!
