### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by oravecz** [malijs/mali#13]
Loved Koa, and now a project needing gRPC and native async/await will be great.

One problem, is it possible to use the [NodeJS cluster module](https://nodejs.org/api/cluster.html) with grpc? I don't have control over my deployment servers and don't want to waste those cores.

**Comment by bojand** [comment]
Hello it doesn't look like `cluster` works smoothly with gRPC at the moment. See relevant issues in `gRPC` repo:

* [NodeJS cluster module](https://github.com/grpc/grpc/issues/6976)
* [support NodeJS cluster mode ?](https://github.com/grpc/grpc/issues/11004)
* [Make grpc node work with node's cluster support.](https://github.com/grpc/grpc/issues/10417)
