### ISSUE TITLE
Request scoped variables

### ISSUE THREAD

**Issue by maxsommer** [malijs/mali#132]
Unless I'm overseeing something currently there is no place to store request scoped variables (e.g. when authenticating somewhen via middleware you extract the payload of their token and would like to store the extracted payload to a variable for this request). ExpressJS has `res.locals` as that place for example.
https://expressjs.com/en/api.html#res.locals
Proposal from my side would be to use something like `ctx.response.locals` or `ctx.response.state`.

**Comment by bojand** [comment]
Hello, can you elaborate specifically on desired behaviour and intent with this, as the express `locals` does not really translate necessarily to gRPC.

Not that you can just set properties within `ctx` and they will be there for the duration of the request. A new context is created for every requests that inherits application level properties. Example:

```js
const path = require('path')
const Mali = require('mali')

const PROTO_PATH = path.resolve(__dirname, '../protos/helloworld.proto')
const HOSTPORT = '0.0.0.0:50051'

function sayHello (ctx) {
  const message = 'Hello ' + ctx.req.name + ' someProp: ' + (ctx.someProp || '') + ' globalProp: ' + (ctx.globalProp || '')
  console.log(message)

  ctx.res = { message }
}

function main () {
  let i = 0
  const app = new Mali(PROTO_PATH, 'Greeter')
  app.context.globalProp = 'bar' // context will always have globalProp = 'bar'

  app.use(async function setProp (ctx, next) {
    if (i % 3 === 0) {
      ctx.someProp = 'foo' // request scoped someProp will be there only some of the time
    }
    next()
    console.log('after response! i: ' + i + ' someProp: ' + (ctx.someProp || '') + ' globalProp: ' + (ctx.globalProp || '') + '\n')
    i++
  })

  app.use({ sayHello })

  app.start(HOSTPORT)
  console.log(`Greeter service running @ ${HOSTPORT}`)
}

main()
```

If we call the service it will result in following output:

```sh
Greeter service running @ 0.0.0.0:50051
Hello world someProp: foo globalProp: bar
after response! i: 0 someProp: foo globalProp: bar

Hello world someProp:  globalProp: bar
after response! i: 1 someProp:  globalProp: bar

Hello world someProp:  globalProp: bar
after response! i: 2 someProp:  globalProp: bar

Hello world someProp: foo globalProp: bar
after response! i: 3 someProp: foo globalProp: bar

Hello world someProp:  globalProp: bar
after response! i: 4 someProp:  globalProp: bar

Hello world someProp:  globalProp: bar
after response! i: 5 someProp:  globalProp: bar

Hello world someProp: foo globalProp: bar
after response! i: 6 someProp: foo globalProp: bar
```

Hope this helps.

**Comment by maxsommer** [comment]
Hi, thanks for the response!
My intent in this case was building a middleware that can extract e.g. a payload from a JWT token set via metadata and make it available as a request scoped variable that I can then use in my controllers.

Issue with just setting the payload as a property inside the context is that with TypeScript I will (rightfully) get an error that whatever property name I'm trying to give my own field – it will not exist on type 'Context' exposed by Mali. Therefore – maybe instead of putting custom fields enhanced via middlewares it might be be helpful to have a specific field where all of those application specific fields go instead of the global Mali.Context scope :)

**Comment by bojand** [comment]
Hello,

Please take a look at #154 and provide feedback.
