### ISSUE TITLE
Compatible with static generator through protobuf.js ?

### ISSUE THREAD

**Issue by briva** [malijs/mali#139]
Hello,

I'm currently trying to use mali with protobuf.js.

my proto :

```
syntax = "proto3";
package root;

service Service {
    rpc Test (Message) returns (Message) {}
}

message Message {
    string message1 = 1;
    string message2 = 2;
}
```

using :

```
pbjs -t static-module -w commonjs -o root.js '*.proto
pbts -o root.d.ts root.js
```

Getting root.js and root.d.ts

After a 

```
const root = require('./root');
```

I try a lot a way to import my basic service through

```
const app = new Mali(root.notification.Service, 'Service');
or
const app = new Mali(root);
or
const app = new Mali(root.notification.Service);
```

But always getting in my client : 

```
details: 'RPC method not implemented /root.Service/Test' }
```

Any clues to solve this issue ? Thx.

**Comment by anonrig** [comment]
Hello, a little bit late to reply but let's leave a reply for other people:

Your app definition should be, since protobuf definition contains `package root`;

```
const app = new Mali(root.notification.Service, 'root.Service');
```
