### ISSUE TITLE
gRPC 1.7.2 doesn't work on Alpine Linux

### ISSUE THREAD

**Issue by yoitsro** [malijs/mali#18]
Firstly, thanks for Mali! You made all of our lives easier :) 

This is not fault of yours, but the binaries for gRPC 1.7.x weren't published for Alpine Linux, therefore preventing Mali 0.4.x working on those distros if the correct build dependencies weren't installed.

It looks like gRPC 1.8.0 has been pre-released: https://github.com/grpc/grpc/issues/11239

This issue is mainly for tracking, but once gRPC 1.8.0 is released along with its binaries, let's get that plugged into Mali :)

**Comment by bojand** [comment]
Thanks for the issue. I usually keep an eye on gRPC node releases so will update it.

Separately, somewhat related, I've been thinking of making `grpc` as a `peerDependancy` that way it's required by users of `mali` on install of `mali` but not depended upon and brought in by Mali explicitly. Similar how `react-router` [peer depends on react](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/package.json#L37). The idea is that users / clients of Mali depend on grpc and they can bring in any version that mali peer depends on that would satisfy. This would probably solve these type of issues in the future. However it would be a breaking change for any current clients that do not depend on `grpc` explicitly themselves; but an easy upgrade of just adding `grpc` dependancy. Thoughts?

**Comment by yoitsro** [comment]
I would be entirely up for making it a `peerDependency`. It makes a lot of sense considering that if the version of gRPC for Mali is different from the version of gRPC the user may be using, the user may have to bundle two native versions of gRPC with their project (depending on the exact versions used).

**Comment by bojand** [comment]
Hello, with the new version `0.6.0` grpc is a `peerDependancy`. Hope this resolves this issue. If not please feel free to reopen.
