### ISSUE TITLE
@grpc/grpc-js compatibility

### ISSUE THREAD

**Issue by Dominoo** [malijs/mali#192]
Hi I have a question, we would like to migrate to grps-js package and I would like to know if and when you are planning support for it since it is not compatible right now 

https://www.npmjs.com/package/@grpc/grpc-js#migrating-from-grpc

I guess only because of the start / startAsync which should not be such a problem. 

I am interested in your point of view

**Comment by mxzinke** [comment]
The original [grpc](https://github.com/grpc/grpc-node) package is running into deprecated in less than one year. Maybe it makes sense to change the dependencies to use the [@grpc/grpc-js](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js) package. After evaluating how much has to be changed, I could do a PR.

But the [migration from grpc](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js), @Dominoo send in looks great to bring in.

Any words on why not to do it?

**Comment by civilizeddev** [comment]
Is there anyone who can lead this?

**Comment by bojand** [comment]
Thanks for creating this issue. Will try and get to this soon.

**Comment by yoitsro** [comment]
Hey @bojand! Let us know if there's anything we can do to help this along :)

**Comment by HappyZombies** [comment]
Any update on this? April is near! I might just make a PR...
