### ISSUE TITLE
Server ephemeral ports

### ISSUE THREAD

**Issue by Americas** [malijs/mali#20]
Hi, when we start a server with port `0`, the server sets up listening on a randomly given port, but there is no way to access the bound port. This behavior is great for testing where we need clean instances of servers, and trying to manage this manually is terrible.

I went diving into the code and found that in [app.start()](https://github.com/malijs/mali/blob/master/lib/app.js#L259), the [server.bind(port, creds)](https://github.com/malijs/mali/blob/master/lib/app.js#L278) call returns the port that the server was bound to.

So my question is, can we save the port on the server object that is returned by `app.start()`? I will gladly submit a PR with this change.

**Comment by bojand** [comment]
Hello thanks for the issue. This is a good idea and an omission in existing API. This should be implemented and published in 0.5.0. Please take a look at the PR #21 for additional documentation. Hopefully this resolved the issue.

**Comment by Americas** [comment]
It works for me, thank you very much :+1:
