### ISSUE TITLE
Mali apps in 0.6.1 are hard to test

### ISSUE THREAD

**Issue by nunofgs** [malijs/mali#23]
Hi @bojand,

First of all, just want to thank you for a great lib. You're doing a great job here.

I was previously using version 0.5.0 and noticed you pushed a major change in 0.6.1 (specifically the `init` function was replaced with `addService`).

Here's a sample implementation of a grpc app in 0.5.0:

```js
// src/app.js

const Mali = require('mali');
const { load } = require('my-grpc-load-function');
const FooService = require('./foo-service');
const BarService = require('./bar-service');

module.exports = function() {
  const app = new Mali();

  // Load proto files.
  // The `load` function returns a proto object using a custom namespace builder. Nothing special, just to allow automatically resolve paths.
  // Also, `load` supports an array since it is simply passed down to `grpc.load`, which also supports an array.
  app.init(load([
    'foo-service',
    'bar-service',
  ]));

  // Register middlewares.
  app.use({ FooService });
  app.use({ BarService });

  // Disable error logging to console.
  app.silent = true;

  return app;
};
```

And here's how I would test it (in 0.5.0):

```js
// test/app.js

const app = require('../src/app')();
const caller = require('grpc-caller');

it('should block the user', async () => {
  const { ports } = app.start();
  const client = caller(`0.0.0.0:${ports[0]}`, app.proto.FooService);
  const result = await client.FooService.doSomething({ foo: 'bar' });

  expect(result).toEqual({ bar: 'biz' });

  app.close();
});
```

When updating to 0.6.1 I hit upon several roadblocks:

1. The `.init()` function was converted to `addService`. The rename didn't break anything by itself but it doesn't really fit in when passing an array (ie: `addService([one, two])`).
2. The `.proto` property is no longer exposed (I understand it was undocumented before, but it was very useful). As it stands, I can see no way to pass the _proto_ object to grpc-caller unless I load the protos again (seems wasteful).

May I ask what your method of testing grpc calls is?

**Comment by bojand** [comment]
Hello, thanks for the feedback and the issue. Just wondering do you not have access to proto(s) or load in `test/app.js` that you can use to create the client? Normally i create a client from proto files in my tests. I think we can probably accommodate something like this in a future release soon. This is not a pattern I use as normally as in real world clients do not have access to the actual app; but I understand there are similar patterns of testing with `supertest` being able to be initialized using an express app.

**Comment by nunofgs** [comment]
> but I understand there are similar patterns of testing with supertest being able to be initialized using an express app.

Yes, exactly. Good call. I'm also using `supertest` for web apps.

> Just wondering do you not have access to proto(s) or load in test/app.js that you can use to create the client?

I do but I also load a few middlewares after loading the protos. For the type of tests I was trying to write, I'd like to execute the grpc method and have it pass through all the middlewares (integration tests).

Do you usually test only the protos themselves?

**Comment by stephen-dahl** [comment]
I would love to see a method that would let me test the framework without calling start.
just load my proto and register my functions then call something like `app.test('someRpcCall', object|stream)`
