### ISSUE TITLE
Add property `state` to the Mali context

### ISSUE THREAD

**Issue by Americas** [malijs/mali#264]
Most requests have information that makes sense to store in a call context. 

In Koa, the context has a `state` property for this purpose, is there a possibility to add a similar property to the Mali context?

**Comment by anonrig** [comment]
Hi @Americas 

You can use `ctx.locals.personal = 'value'` on your handler. According to our docs `locals` are Request-scoped local variables. You can place anything you wish here.

**Comment by Americas** [comment]
Huh, failed to see that one :smile: Thanks!

**Comment by anonrig** [comment]
No worries. Have a great day!
