### ISSUE TITLE
Protos which depend on a namespace which contains a `type` key prevents loading of the services

### ISSUE THREAD

**Issue by eeston** [malijs/mali#270]
**Describe the bug**
As part of the optimisation work done [recently](https://github.com/malijs/mali/commit/12b46062ff3a8790f3fa7f4ceed0e82fc19c4a36), [this line](https://github.com/malijs/mali/blob/master/lib/utils.js#L69) is preventing our services from being loaded and started by Mali.

The reported error is:

```
Could not start server! TypeError: Unknown method: listUsers
    at Mali.use (/Users/john/Developer/app/node_modules/mali/lib/app.js:217:21)
```

**To Reproduce**

Create the following protocol buffers:

### `protos/app/users/v1/users_service.proto`

```
syntax = "proto3";

package app.users.v1;

import "app/type/v1/name.proto";

service UsersService {
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {}
}

message ListUsersRequest {
  string search = 1;
}

message ListUsersResponse {
  int64 count = 1;
  repeated User results = 2;
}

message User {
  app.type.v1.Name name = 1;
}
```

### `protos/app/type/v1/name.proto`

```
syntax = "proto3";

package app.type.v1;

message Name {
  string first = 1;
  string last = 2;
}
```

### Create a server

```
const main = async () => {
  const app = new Mali(
      "./protos/app/users/v1/users_service.proto",
      "app.users.v1.UsersService",
      {
        keepCase: true,
        longs: Number,
        defaults: true,
        oneofs: true,
        includeDirs: ["./protos"],
      }
    );

    app.use({
      listUsers: (ctx) => { ctx.res = { first: "First", last: "Last" } },
    });

    await app.start(`0.0.0.0:0`);
}

main()
  .then(() => console.log("Running!")
  .catch((error) => console.error(error));
```

**Expected behavior**
I expected my service to start with no issues.

**Environment**
 - Version: 0.44.1
 - Node.js version: 14.17.1
 - OS: MacOS 11.4

**Comment by anonrig** [comment]
Wow this is a good one. Thanks for the fantastic bug report. I'll take a look at it asap.

**Comment by anonrig** [comment]
I've released a new version (0.44.2) fixing this. Hope it helps @eeston, thank you for the bug report. I hope not to see a similar bug report again in the future :))

**Comment by eeston** [comment]
Thanks for the quick fix @anonrig. I'll test the update this evening 👍

**Comment by eeston** [comment]
No more issues! Thanks again @anonrig
