### ISSUE TITLE
Metadata `add` vs `set`

### ISSUE THREAD

**Issue by Americas** [malijs/mali#283]
When calling the `Metadata.create()` defined in [this file](https://github.com/malijs/mali/blob/master/lib/metadata.js) the newly created Metadata object is populated by calling `add`, which first does a get to see if the property is set, and only then performs the set.

For an empty Metadata object, this is useless, why not use the `set` method, and skip the get call?

**Comment by anonrig** [comment]
Thank you for the issue and question. Since keys in the metadata parameter is unique, there's no need to check for existing keys. You're right. 🎉  

I believe this will improve the performance of creating metadatas. Can you create a pull request for this?

**Comment by Americas** [comment]
Yes, I can do the change 😄
