### ISSUE TITLE
FeatureRequest: port awilix-koa to mali

### ISSUE THREAD

**Issue by zj8487** [malijs/mali#29]
Hi @bojand,

First of all, just want to thank you for a great lib. You're doing a great job here.

I was previously using [awilix](https://github.com/jeffijoe/awilix) and [awilix-koa](https://github.com/jeffijoe/awilix-koa). and it is very graceful.
if it possible to port awilix to mali. i think it will be very cool.

thank you very much!

**Comment by bojand** [comment]
Hello thanks for the praise and the suggestion. awilix is not something I am familiar with so I'll have to take a look. Quickly looking at `awilix-koa` and the "basic usage" API section and relevant source code, it seems to be only clean koa middleware that interacts with the `context` and `next` params, but does not depend on underlying `request` / `response` properties and thus on the actual transport mechanism. I imagine the API in the "Awesome Usage" section does use the router and underlying transport mechanism. I would suggest perhaps just trying `awilix-koa` with Mali using the "basic usage" API (ie `scopePerRequest`). It may actually "just work" and be sufficient until I take a more deeper look into this.
