### ISSUE TITLE
gRPC Server Options

### ISSUE THREAD

**Issue by JamesNyamu** [malijs/mali#34]
- If binary messages are too large an error
`Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4416819 vs. 4194304)` is thrown
- One should be able to initialize the gRPC server with options such as
`var server = new grpc.Server({'grpc.max_send_message_length': 1024*1024*1024})`

**Comment by JamesNyamu** [comment]
I have resolved this issue but I do not have permissions to push a branch and create a PR.

**Comment by bojand** [comment]
I think I see the issue. How are you initializing the app? Can you please provide some sample code that demonstrates the issue. Also you should be able to fork and then do a PR.

**Comment by ProfNandaa** [comment]
Ping @JamesNyamu ^^^
