### ISSUE TITLE
How to set deadline

### ISSUE THREAD

**Issue by jnst** [malijs/mali#61]
* [gRPC and Deadlines](https://grpc.io/blog/deadlines)

If there is [no document](https://mali.js.org/guide/context.html), could you append it?
If there is no feature, it will be a request to add a feature.

**Comment by bojand** [comment]
Hello,

In gRPC some languages use timeout values (ex. Go) and some use deadlines, that is a future point in time when timeout expires. For Node.js a deadline is used. The deadline can be set on client side like this (using the [greeter example](https://github.com/malijs/examples/tree/master/hello_world_dynamic)):

```js
const path = require('path')
const protoLoader = require('@grpc/proto-loader')
const grpc = require('grpc')

const PROTO_PATH = path.resolve(__dirname, '../protos/helloworld.proto')

const pd = protoLoader.loadSync(PROTO_PATH)
const loaded = grpc.loadPackageDefinition(pd)
const helloProto = loaded.helloworld

function main () {
  var client = new helloProto.Greeter('localhost:50051', grpc.credentials.createInsecure())
  var user
  if (process.argv.length >= 3) {
    user = process.argv[ 2 ]
  } else {
    user = 'world'
  }

  const deadline = new Date().setSeconds(new Date().getSeconds() + 5)

  const md = new grpc.Metadata()
  md.add('request-id', '12345')

  client.sayHello({ name: user }, md, { deadline }, function (err, response) {
    if (err) {
      console.log(err.message)
    }

    if (response) {
      console.log('Greeting:', response.message)
    }
  })
}

main()
```

On the server we can get whether the call has been cancelled using `ctx.call.cancelled` property:

```js
const path = require('path')
const Mali = require('mali')
const grpc = require('grpc')
const delay = require('delay')

const PROTO_PATH = path.resolve(__dirname, '../protos/helloworld.proto')
const HOSTPORT = '0.0.0.0:50051'

function sayHello (ctx) {
  if (ctx.call.cancelled) {
    const err = new Error(`Cancelled: ${ctx.get('request-id')}`)
    err.code = grpc.status.CANCELLED
    throw err
  }

  ctx.res = { message: 'Hello ' + ctx.req.name }
}

async function timeout (ctx, next) {
  await delay(2100)
  return next()
}

function main () {
  const app = new Mali(PROTO_PATH, 'Greeter')
  app.use(timeout)
  app.use({ sayHello })
  app.start(HOSTPORT)
  console.log(`Greeter service running @${HOSTPORT} `)
}

main()

```

The `timeout` middleware is simulating some kind of wait for the request. For example if we use `await delay(2100)` in the `timeout` middleware everything works out fine. If we use `await delay(5100)` which is above the deadline, the request times out. When our handler is reached the `ctx.call.cancelled` property is `true` and we can handle the request differently in such a scenario (ie, log it). Here we're just throwing an error as an example, and we get the error logged:

```sh
Error: Cancelled: 12345
      at sayHello (/malijs/examples/hello_world_dynamic/greeter_server.js:14:17)
      at dispatch (/malijs/examples/node_modules/mali-compose/index.js:48:32)
      at timeout (/malijs/examples/hello_world_dynamic/greeter_server.js:24:10)
      at <anonymous>
```

On the client side we get:

```sh
4 DEADLINE_EXCEEDED: Deadline Exceeded
```

Hope this helps.

It may be useful to alias `cancelled` into `ctx` like we do for other properties, so I may add that in the future. Will also try and add documentation about handling this.

**Comment by jnst** [comment]
I'm sorry. This was a client-side topic.
Thank you very much. I really appreciate your thoughtfulness. 😃
