### ISSUE TITLE
Unclear how to set `ctx.res` in TypeScript implementation

### ISSUE THREAD

**Issue by peterwhitesell** [malijs/mali#75]
https://github.com/malijs/mali/pull/53 added TypeScript type definitions, but I'm having trouble figuring out how to use the simple examples from the docs. Following the docs (https://mali.js.org/guide/context.html#context), in my handler I set `ctx.res = { foo: 'bar' }` to set the response value, which leads to the TypeScript error `Type '{ status: ServingStatus; }' is not assignable to type 'GrpcResponse'`.

It seems to me the union type of `GrpcResponse` should include `any`, because you're supposed to be able to set the res property to the actual response message / object. https://mali.js.org/guide/context.html#ctx-res
> In all other cases set the res property to the actual response message / object in case of UNIRY and REQUEST_STREAM calls, and to the output stream in case of RESPONSE_STREAM calls

Am I understanding this right? What is the proper way to set `Context.res` in TypeScript?

**Comment by bojand** [comment]
Hello can you please try [0.12.0](https://github.com/malijs/mali/releases/tag/v0.12.0).

**Comment by yosiat** [comment]
@bojand I am trying to use 0.12.0 and I am getting this compilation error:
```
> tsc

node_modules/mali/index.d.ts:44:10 - error TS2314: Generic type 'GrpcRequest' requires 1 type argument(s).

44     req: GrpcRequest;
            ~~~~~~~~~~~

node_modules/mali/index.d.ts:45:10 - error TS2314: Generic type 'GrpcResponse' requires 1 type argument(s).

45     res: GrpcResponse;
            ~~~~~~~~~~~~

node_modules/mali/index.d.ts:60:10 - error TS2314: Generic type 'GrpcRequest' requires 1 type argument(s).

60     req: GrpcRequest;
            ~~~~~~~~~~~

node_modules/mali/index.d.ts:72:10 - error TS2314: Generic type 'GrpcResponse' requires 1 type argument(s).

72     res: GrpcResponse;
            ~~~~~~~~~~~~


Found 4 errors.
```

This is my service code
```typescript
import * as logger from 'mali-logger';
import * as Mali from 'mali';
import { resolve } from 'path';

const PROTO_PATH = resolve(__dirname, '../protos/helloworld.proto');
console.log('Proto Path', PROTO_PATH);

async function sayHello(ctx) {
  console.log(ctx);
  ctx.res = {message: 'Hello '.concat(ctx.req.name)};
}

function main() {
  const app = new Mali(PROTO_PATH);
  app.use(logger());

  app.use({sayHello});
  console.log('> listening on 127.0.0.1:50051');
  app.start('127.0.0.1:50051');
}

main();
```

**Comment by bojand** [comment]
Hello, I have updated type definitions again in [0.13.0](https://github.com/malijs/mali/releases/tag/v0.13.0), setting the request and response types to `any` which I believe should work now.

**Comment by yosiat** [comment]
Hi @bojand settings the types to `any` solves the issue currently but no the root issue.

@sykorax  wrote here the best solution - https://github.com/malijs/mali/issues/43#issuecomment-472823653

Ideally, I would like to write the next code:
```typescript
async function sayHello(ctx: Contect<GreetRequest, GreetResponse>) {
  console.log(ctx);
  ctx.res = {message: 'Hello '.concat(ctx.req.name)};
}
```

if we can make this happen I will try to write typescript generator for protobuf that supports mali convention of `ctx`

**Comment by bojand** [comment]
Hello,

I believe this should be addressed in 0.17.0.

**Comment by joemckie** [comment]
This is still an issue in 0.19.0. `GrpcRequest` and `GrpcResponse` are now set to be `any`, resulting in having to do something like the following:

```ts
const request: HelloRequest = ctx.req;
```

It seems like `Context` should be generic and can fall back to `any` if no params are given. This shouldn't be too hard, if there's no issues with it I'm happy to submit a PR?

**Comment by anonrig** [comment]
If this issue is not solved, please open a new issue. I'll be happy to address it.
