### ISSUE TITLE
Is compatible with protobufjs?

### ISSUE THREAD

**Issue by sykorax** [malijs/mali#79]
I was wondering if it is compatible with the generated sources by protobufjs package.

I am looking for a solution to generate both server interfaces and client stubs in typescript. Sadly i could not find any official workaround yet however protobufjs seems to be a doable way.

Do you have any other recommendation?

**Comment by bojand** [comment]
Hello, can you elaborate more on the issue as I am not sure I understand completely. Mali uses the official [grpc module](https://www.npmjs.com/package/grpc), which in turn [uses protobufjs](https://github.com/grpc/grpc-node/blob/grpc%401.19.0/packages/grpc-native-core/package.json#L36). I do not really use TypeScript so not sure how that factors into this.

**Comment by sykorax** [comment]
Sorry, 
It is my fault. Figured it finally. :)
