### ISSUE TITLE
Adding an endware does not work

### ISSUE THREAD

**Issue by kashifmin** [malijs/mali#83]
Hi, @bojand 
I have the following setup:
```js
app.use(maliLogger({ fullName: true }));
app.use({ MyService: serviceFunctions });
```

Now want to add an endware that JSON.stringifies a field in `ctx.res`.
For example:
`app.use(toJSONString('myFieldName'));`

But `toJSONString` middleware is never called.
I tried calling `next()` in all my service function, but the app crashes with the following error:
`
TypeError: key.indexOf is not a function
    at Mali._getMatchingServiceName (/Users/blah/node_modules/mali/lib/app.js:472:13) 
`

Is this an issue or am I doing something wrong?

**Comment by bojand** [comment]
Hello, can you please provide full reproducible source code and error call stack. There is very little information here to go on. Where and when are you adding the custom `toJSONstring()` middleware? What does it do? I cannot reproduce this with a simple test:

```js
const path = require('path')
const Mali = require('mali')
const maliLogger = require('@malijs/logger')

const PROTO_PATH = path.resolve(__dirname, 'test/protos/helloworld.proto')

async function sayHello (ctx) {
  ctx.res = { message: 'Hello '.concat(ctx.req.name) }
}

async function logger (ctx, next) {
  const start = new Date()
  await next()
  const ms = new Date() - start
  console.log('%s [%s] - %s ms', ctx.name, ctx.type, ms)
}

function main () {
  const app = new Mali(PROTO_PATH)

  app.use(maliLogger({ fullName: true }))
  app.use(logger)
  app.use({ sayHello })

  app.start('127.0.0.1:50051')
}

main()
```

Results in correct output:

```
 --> /helloworld.Greeter/SayHello unary
SayHello [unary] - 0 ms
  <-- /helloworld.Greeter/SayHello unary 0ms
```

**Comment by kashifmin** [comment]
Hi @bojand 
This was caused by a silly bug in my code.
```js
async function toJsonString(field) {
  return async function toJson(ctx, next) {
    await next();
    if (ctx.res && ctx.res[field] && typeof ctx.res[field] !== 'string') {
      ctx.res[field] = JSON.stringify(ctx.res[field]);
    }
  };
}
```

The wrapper function for middleware had the `async` keyword which is not correct. I've removed the `async` and now it is working as expected.
Thank you and sorry for this silly mistake.
