### ISSUE TITLE
app.ports is not a function

### ISSUE THREAD

**Issue by colq2** [malijs/mali#93]
Hello,
according to the [documentation ](https://mali.js.org/guide/application.html#start) the function `ports()` exists on the app object.
But I'm getting the error `TypeError: app.ports is not a function`.

With `let ports = app.ports` everything works like expected.

**Comment by bojand** [comment]
Hello, sorry the documentation on that page was incorrect. `ports` is just a property of the application object, and not a function. I have update the documentation. Thank you for pointing this out.
